EMAIL_MAX_LENGHT = 254
ROLE_MAX_LENGHT = 10
CODE_MAX_LENGHT = 100
USERNAME_MAX_LENGHT = 150
USER = "user"
MODERATOR = "moderator"
ADMIN = "admin"

ME = ["me", ADMIN, MODERATOR, USER]
USERNAME_MIN_LENGHT = 3
